version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  app:
    build: ../steve
    links:
      - "db:mariadb"
    volumes:
      - ../steve:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - db

  libocpp:
    build: 
      context: .
      dockerfile: Dockerfile.chargepoint
    tty: true
    stdin_open: true
    # ports:
    #   - "8180:8180"
