name: Feature Request
description: Thanks for taking the time to fill out this feature request!

body:
  - type: dropdown
    id: affected-ocpp-version
    attributes:
      label: OCPP Version
      description: For which OCPP do you suggest this feature? Mark both if applicable.
      options:
        - OCPP1.6
        - OCPP2.0.1
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.

  - type: textarea
    id: reproduction
    attributes:
      label: Describe your solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Additional context
      placeholder: Add any other context about the feature request here.
