-- Transactions --
CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID TEXT PRIMARY KEY NOT NULL, --0--
    SEQ_NO INT NOT NULL, --1--
    EVSE_ID INT NOT NULL, --2--
    CONNECTOR_ID INT NOT NULL, --3--
    TIME_START INT64 NOT NULL, --4--
    CHARGING_STATE TEXT NOT NULL, --5--
    ID_TAG_SENT INT NOT NULL --6--
);
