-- Transactions --
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID TEXT PRIMARY KEY NOT NULL,
    SEQ_NO INT NOT NULL,
    MESSAGE_TYPE TEXT NOT NULL,
    EVSE_ID INT NOT NULL,
    CONNECTOR_ID INT NOT NULL,
    ID_TOKEN TEXT NOT NULL,
    TIME_START INT64 NOT NULL,
    CHARGING_STATE TEXT NOT NULL,
    RESERVATION_ID INT,
);
