-- We need to go via a temporary table since LAST_USED must be NOT NULL but should not have a default
CREATE TABLE AUTH_CACHE_TEMP (
    ID_TOKEN_HASH TEXT PRIMARY KEY NOT NULL,
    ID_TOKEN_INFO TEXT NOT NULL,
    LAST_USED INT64 NOT NULL,
    EXPIRY_DATE INT64
);

-- Copy over values to new table inserting default LAST_USED of -1
INSERT INTO AUTH_CACHE_TEMP (ID_TOKEN_HASH, ID_TOKEN_INFO, LAST_USED) SELECT ID_TOKEN_HASH, ID_TOKEN_INFO, '-1' FROM AUTH_CACHE;

DROP TABLE AUTH_CACHE;
ALTER TABLE AUTH_CACHE_TEMP RENAME TO AUTH_CACHE;
