CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID TEXT PRIMARY KEY NOT NULL,
    SEQ_NO INT NOT NULL,
    EVSE_ID INT NOT NULL,
    CONNECTOR_ID INT NOT NULL,
    TIME_START INT64 NOT NULL,
    CHARGING_STATE TEXT NOT NULL,
    ID_TAG_SENT INT NOT NULL
);
