@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
participant csms order 10
participant libocpp order 20
participant core order 30
actor user order 40 
autonumber "<b><font color=red>"
skinparam sequenceArrowThickness 2

== Start a transaction ==
user->core: swipe ID tag
user->core: plug in cable
core->libocpp: Authorize
libocpp->core:Authorized
core->libocpp: on_transaction_started()
core->core: insert_transaction(transaction_id,\nstart_time,id_token_info)
libocpp->csms: TransactionEventRequest::Started
libocpp->csms: (Optional) TransactionEventRequest::Updated

== System Failure / Power Outage ==
core->core: Booting process
core->libocpp: ChargePoint::start()
libocpp->csms: BootNotification Request
csms->libocpp: Bootnotification Response
libocpp->libocpp: restore values from database
alt TransactionInteruptedResponse.has_interrupted_transaction = true
core->core: Restore authorization
libocpp->libocpp: resume_interrupted_transactions()
libocpp->csms: (optional) TransactionEventRequest::Updated
user->core: swipe ID tag
user->core: unplug cable
core->libocpp: on_transaction_finished()
libocpp->libocpp: clear_transaction(transaction_id)
libocpp->csms: TransactionEventRequest::Ended

else TransactionInteruptedResponse.has_interrupted_transaction = false
note over core: continue normal operations



@enduml