name: Build and test libocpp

on:
  push:

jobs:

  build_and_test:
    uses: EVerest/everest-core/.github/workflows/build_and_test.yaml@CI/reusable-workflow
    with:
      repository: EVerest/libocpp
      repository_ref: CI/reusable-workflow  # TODO use a context-variable instead
