name: Build and test libocpp

on:
  push:


jobs:
  build_and_test:
    uses: EVerest/everest-core/.github/workflows/build_and_test.yaml@CI/reusable-workflow
    with:
      unit_tests: true
      integration_tests: false
      repository: EVerest/libocpp
      repository_ref: ${{ github.head_ref || github.ref_name }}
